######################################################################
# Automatically generated by qmake (3.1) Wed Nov 18 21:18:14 2020
######################################################################

TEMPLATE = app
TARGET = InteractiveScene
INCLUDEPATH += . /opt/local/include

QT += widgets opengl gui 
LIBS += -lGLU

# Input
HEADERS += MainWindow.h SceneWidget.h Mesh.h
SOURCES += Main.cpp MainWindow.cpp SceneWidget.cpp Mesh.cpp
